# action.yml
name: 'Firebase distribution'
description: 'Deploy to firebase distribution'
inputs:
  cli-token:  # id of input
    description: 'firebase cli auth token'
    required: true
  app-id:  # id of input
    description: 'firebase id of the app'
    required: true
  groups:
    description: "tester groups, separated by comma"
    required: false
    default: ""

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cli-token }}
    - ${{ inputs.app-id }}
    - ${{ inputs.groups }}
